/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.vanzyl.harbor.client.okhttp.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * LdapUser
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-25T17:57:51.873-04:00")
public class LdapUser {
  @SerializedName("username")
  private String username = null;

  @SerializedName("realname")
  private String realname = null;

  @SerializedName("email")
  private String email = null;

  public LdapUser username(String username) {
    this.username = username;
    return this;
  }

   /**
   * ldap username.
   * @return username
  **/
  @ApiModelProperty(value = "ldap username.")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public LdapUser realname(String realname) {
    this.realname = realname;
    return this;
  }

   /**
   * The user realname from \&quot;uid\&quot; or \&quot;cn\&quot; attribute.
   * @return realname
  **/
  @ApiModelProperty(value = "The user realname from \"uid\" or \"cn\" attribute.")
  public String getRealname() {
    return realname;
  }

  public void setRealname(String realname) {
    this.realname = realname;
  }

  public LdapUser email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The user email address from \&quot;mail\&quot; or \&quot;email\&quot; attribute.
   * @return email
  **/
  @ApiModelProperty(value = "The user email address from \"mail\" or \"email\" attribute.")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LdapUser ldapUser = (LdapUser) o;
    return Objects.equals(this.username, ldapUser.username) &&
        Objects.equals(this.realname, ldapUser.realname) &&
        Objects.equals(this.email, ldapUser.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(username, realname, email);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LdapUser {\n");
    
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    realname: ").append(toIndentedString(realname)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

