/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.vanzyl.harbor.client.okhttp.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * LdapFailedImportUser
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-25T17:57:51.873-04:00")
public class LdapFailedImportUser {
  @SerializedName("uid")
  private String uid = null;

  @SerializedName("error")
  private String error = null;

  public LdapFailedImportUser uid(String uid) {
    this.uid = uid;
    return this;
  }

   /**
   * the uid can&#39;t add to system.
   * @return uid
  **/
  @ApiModelProperty(value = "the uid can't add to system.")
  public String getUid() {
    return uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }

  public LdapFailedImportUser error(String error) {
    this.error = error;
    return this;
  }

   /**
   * fail reason.
   * @return error
  **/
  @ApiModelProperty(value = "fail reason.")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LdapFailedImportUser ldapFailedImportUser = (LdapFailedImportUser) o;
    return Objects.equals(this.uid, ldapFailedImportUser.uid) &&
        Objects.equals(this.error, ldapFailedImportUser.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uid, error);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LdapFailedImportUser {\n");
    
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

